version: 1.4.10

pod:
  replicaCount: 1
  image: iwnet/hbase-master
  tag: latest
  pullPolicy: Never

service: #{}
  type: ClusterIP #

name: bda-hbase-master

resources: #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: "128Mi"
    cpu: "300m"
  #limits:
  #  memory: 1024Mi
  #  cpu: 1

ports:
  hbaseMaster1: 60010
  hbaseMaster2: 16000
  hbaseMaster3: 16010