version: 2.9.1

statefulset:
  replicaCount: 1
  image: iwnet/hadoop-yarn-resourcemanager
  tag: latest
  pullPolicy: Never

service: #{}
  type: None #ClusterIP #

name: bda-hadoop-yarn-resourcemanager

resources: #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: "128Mi"
    cpu: "300m"
  #limits:
  #  memory: 1024Mi
  #  cpu: 1

ports:
  rm_address0: 8030
  rm_address1: 8031
  rm_address2: 8032
  rm_address3: 8033
  rm_web: 8088