
statefulset:
  replicaCount: 1
  image: iwnet/postgres
  tag: latest
  pullPolicy: Never

service: #{}
  type: None #ClusterIP #

name: bda-postgres

resources: #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: "128Mi"
    cpu: "300m"
  #limits:
  #  memory: 1024Mi
  #  cpu: 1

ports:
  postgresPort: 5432


config:
  name: postgres-config
  user: postgres
  password: 

pv:
  storage: 2Gi
  name: data
  path: /var/lib/postgresql/data
  subpath: postgres
  accessModes: ReadWriteOnce
  className: "standard"
