apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: fs
    port: {{ .Values.ports.fs }}
  - name: fs2
    port: {{ .Values.ports.fs2 }}
  - name: web
    port: {{ .Values.ports.web }}
  {{- if .Values.service.type }}
    {{- if eq .Values.service.type "None"}}
  clusterIP: None
    {{- else}} 
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- end}}
  {{- else}}  
  type: ClusterIP
  {{- end}}