apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: zookeeper-port
    port: {{ .Values.ports.mainPort }}
    protocol: TCP
  - name: server
    port: {{ .Values.ports.server }}
  - name: leader-election
    port: {{ .Values.ports.leaderElection }}
  {{- if .Values.service.type }}
    {{- if eq .Values.service.type "None"}}
  clusterIP: None
    {{- else}} 
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- end}}
  {{- else}}  
  type: ClusterIP
  {{- end}}