apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1}}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        env:
        - name: KAFKA_OAUTH_SERVER_PROP_FILE
          value: /code/conf/bda.properties
        {{- if .Values.resources }}
        resources:
          {{- if .Values.resources.requests }}
          requests:
            memory: {{ .Values.resources.requests.memory | default "128Mi" | quote }}
            cpu: {{ .Values.resources.requests.cpu | default "500m" | quote }}
          {{- else}}
          requests:
            memory: "128Mi"
            cpu: "300m"
          {{- end}}
          {{- if .Values.resources.limits }}
          limits:
            memory: {{ .Values.resources.limits.memory | default "1024Mi" | quote }}
            cpu: {{ .Values.resources.limits.cpu | default "1" | quote }}
          {{- else}}  
          #limits:
          #  memory: "1024Mi"
          #  cpu: "1"
          {{- end }}
        {{- else }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "300m"
          #limits:
          #  memory: "1024Mi"
          #  cpu: "1"
        {{- end}} 
        ports:
        - containerPort: {{ .Values.ports.bdaPort }}
          name: bda-port
        volumeMounts:
        - name: {{ .Values.pv.name }}
          mountPath: {{ .Values.pv.path }}
      volumes:
        - name: {{ .Values.pv.name }}
          hostPath:
            # directory location on host
            path: {{ .Values.pv.hostPath }}
            type: {{ .Values.pv.type }}
    #   nodeSelector:
    #     kubernetes.io/hostname: {{ .Values.nodeSelector }}
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       podAffinityTerm:
      #         labelSelector:
      #           matchLabels:
      #             app: {{ .Values.name }}
      #         topologyKey: kubernetes.io/hostname
                    
      

      

                
      
