apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  {{- if .Values.service.type }}
    {{- if eq .Values.service.type "None"}}
  clusterIP: None
    {{- else}} 
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- end}}
  {{- else}}  
  type: ClusterIP
  {{- end}}
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      name: bda-port
      port: {{ .Values.ports.bdaPort }}
      targetPort: {{ .Values.ports.bdaPort }}
      nodePort: {{ .Values.ports.nodePort }} # Port to allocate on host. The range of valid ports is 30000-32767.
#externalIPs:
# {{- range $extIP := .Values.externalIPs.ip }} 
#     - {{ $extIP | quote }}
# {{- end }}