apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      name: kafka-port1
      port: {{ .Values.ports.kafkaPort1 }}
      targetPort: {{ .Values.ports.kafkaPort1 }}
    - protocol: TCP
      name: kafka-port2
      port: {{ .Values.ports.kafkaPort2 }}
      targetPort: {{ .Values.ports.kafkaPort2 }}
  {{- if .Values.service.type }}
    {{- if eq .Values.service.type "None"}}
  clusterIP: None
    {{- else}} 
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- end}}
  {{- else}}  
  type: ClusterIP
  {{- end}}
