apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      name: hbase-master-p
      port: {{ .Values.ports.hbaseMaster1 }}
      targetPort: {{ .Values.ports.hbaseMaster1 }}
    - protocol: TCP
      name: hbase-master-p2
      port: {{ .Values.ports.hbaseMaster2 }}
      targetPort: {{ .Values.ports.hbaseMaster2 }}
    - protocol: TCP
      name: hbase-master-p3
      port: {{ .Values.ports.hbaseMaster3 }}
      targetPort: {{ .Values.ports.hbaseMaster3 }}
  {{- if .Values.service.type }}
    {{- if eq .Values.service.type "None"}}
  clusterIP: None
    {{- else}} 
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- end}}
  {{- else}}  
  type: ClusterIP
  {{- end}}