kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
   - name: rm-address0
     port: {{ .Values.ports.rm_address0 }}
     targetPort: {{ .Values.ports.rm_address0 }}
   - name: rm-address1
     port: {{ .Values.ports.rm_address1 }}
     targetPort: {{ .Values.ports.rm_address1 }}
   - name: rm-address2
     port: {{ .Values.ports.rm_address2 }}
     targetPort: {{ .Values.ports.rm_address2 }}
   - name: rm-address3
     port: {{ .Values.ports.rm_address3 }}
     targetPort: {{ .Values.ports.rm_address3 }}   
   - name: rm-web
     port: {{ .Values.ports.rm_web }}
     targetPort: {{ .Values.ports.rm_web }}
  {{- if .Values.service.type }}
    {{- if eq .Values.service.type "None"}}
  clusterIP: None
    {{- else}} 
  type: {{ .Values.service.type | default "ClusterIP" }}
    {{- end}}
  {{- else}}  
  type: ClusterIP
  {{- end}}