version: 0.6.0-incubating

deployment:
  replicaCount: 1
  image: iwnet/livy
  tag: latest
  pullPolicy: Never

service: #{}
  type: ClusterIP #None

name: bda-livy

resources: #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: "128Mi"
    cpu: "300m"
  #limits:
  #  memory: 1024Mi
  #  cpu: 1

ports:
  livyPort: 8998