apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    app: {{ .Values.name }}
data:
  POSTGRES_PASSWORD: {{ .Values.config.password }}
  POSTGRES_USER: {{ .Values.config.user }}

