apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    app: {{ .Values.name }}
data:
  KEYCLOAK_PASSWORD: {{ .Values.config.password }}
  KEYCLOAK_USER: {{ .Values.config.user }}
  LANG: en_US.UTF-8
  DB_VENDOR: postgres
  DB_ADDR: bda-postgres
  KEYCLOAK_IMPORT: /tmp/test-realm.json
