version: 0.1.0

deployment:
  replicaCount: 1
  image: iwnet/bda
  tag: latest
  pullPolicy: Never

hpa:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 1
  averageCPUUtilization: 50

service: #{}
  type: NodePort #LoadBalancer

externalIPs:
  ip:
  - 10.0.1.213
  - 10.0.1.210
  - 10.0.1.194

ports:
  bdaPort: 9999
  nodePort: 30000

name: bda-controller

resources: #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: "128Mi"
    cpu: "300m"
  #limits:
  #  memory: 1024Mi
  #  cpu: 1


pv:
  storage: 2Gi
  name: code-path
  path: /code
  hostPath: /home/ubuntu/shared-bigdata-infra
  type: Directory


#nodeSelector: k8s-worker-1
